version: "3"
services:
  redis:
    image: redis
    ports:
      - "127.0.0.1:6380:6379"
    user: "redis:redis"
  s3:
    image: lphoward/fake-s3
    ports:
      - "127.0.0.1:4569:4569"
    volumes:
      - ./fakes3:/fakes3_root
